version: "3.7"
services:
  php-apache:
    build: "docker/php-apache/"
    container_name: "api-php-apache"
    volumes:
      - ./:/var/www/html
    depends_on:
      - api-mysql
    restart: always
    ports:
      - "8081:80"
  api-mysql:
    image: mysql:5.7
    container_name: "api-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "directus"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    restart: always
    expose:
      - "3306"
